//! Hand-declared Pango ABI: never translate glib headers into Zig.
pub const Layout = opaque {};
pub const Font = opaque {};
pub const Iter = opaque {};
pub const Line = opaque {};
pub const Rectangle = extern struct { x: c_int, y: c_int, width: c_int, height: c_int };
pub extern fn pango_cairo_create_layout(*anyopaque) ?*Layout;
pub extern fn pango_cairo_update_layout(*anyopaque, *Layout) void;
pub extern fn pango_cairo_show_layout_line(*anyopaque, *Line) void;
pub extern fn pango_layout_set_text(*Layout, [*]const u8, c_int) void;
pub extern fn pango_layout_set_width(*Layout, c_int) void;
pub extern fn pango_layout_set_wrap(*Layout, c_int) void;
pub extern fn pango_layout_set_font_description(*Layout, *Font) void;
pub extern fn pango_font_description_from_string([*:0]const u8) ?*Font;
pub extern fn pango_font_description_set_absolute_size(*Font, f64) void;
pub extern fn pango_font_description_free(*Font) void;
pub extern fn pango_layout_get_pixel_size(*Layout, *c_int, *c_int) void;
pub extern fn pango_layout_get_extents(*Layout, ?*Rectangle, *Rectangle) void;
pub extern fn pango_layout_get_text(*Layout) [*:0]const u8;
pub extern fn pango_layout_get_cursor_pos(*Layout, c_int, *Rectangle, ?*Rectangle) void;
pub extern fn pango_layout_xy_to_index(*Layout, c_int, c_int, *c_int, *c_int) c_int;
pub extern fn pango_layout_get_iter(*Layout) ?*Iter;
pub extern fn pango_layout_iter_free(*Iter) void;
pub extern fn pango_layout_iter_get_line_readonly(*Iter) *Line;
pub extern fn pango_layout_iter_get_line_extents(*Iter, ?*Rectangle, *Rectangle) void;
pub extern fn pango_layout_iter_get_baseline(*Iter) c_int;
pub extern fn pango_layout_iter_next_line(*Iter) c_int;
pub extern fn pango_layout_get_line_readonly(*Layout, c_int) ?*Line;
pub extern fn pango_layout_line_get_start_index(*Line) c_int;
pub extern fn pango_layout_line_get_x_ranges(*Line, c_int, c_int, *?[*]c_int, *c_int) void;
pub extern fn pango_get_log_attrs([*]const u8, c_int, c_int, ?*anyopaque, [*]u32, c_int) void;
pub extern fn g_object_unref(*anyopaque) void;
pub extern fn g_free(?*anyopaque) void;
